# Generated by Django 3.0.3 on 2020-02-24 09:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('account_no', models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999)])),
                ('pin', models.IntegerField(blank=True, help_text='Required. 6 digits or fewer.  digits', null=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('username', models.CharField(blank=True, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, null=True, unique=True, verbose_name='username')),
                ('DOB', models.DateField()),
                ('Address', models.TextField()),
                ('password', models.CharField(blank=True, help_text='Required. 30 characters or fewer. Letters, digits and special characters', max_length=30, null=True, verbose_name='password')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneysent', models.DecimalField(decimal_places=2, default=2000, max_digits=12)),
                ('reason', models.TextField(blank=True, null=True)),
                ('receivers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiveracc', to='NetBanking.Account')),
                ('senders', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='senderacc', to='NetBanking.Account')),
            ],
        ),
        migrations.CreateModel(
            name='AccountTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawdetails', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('depositdetails', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounttransactions', to='NetBanking.Account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='NetBanking.Users'),
        ),
    ]
