# Generated by Django 3.0.3 on 2020-02-24 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NetBanking', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountTransactions',
        ),
    ]
