# Generated by Django 3.0.3 on 2020-02-19 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NetBanking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transations',
            name='receivers_account',
        ),
        migrations.RemoveField(
            model_name='transations',
            name='senders_account',
        ),
        migrations.AddField(
            model_name='transations',
            name='receivers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiveracc', to='NetBanking.Account'),
        ),
        migrations.AddField(
            model_name='transations',
            name='senders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='senderacc', to='NetBanking.Account'),
        ),
        migrations.AlterField(
            model_name='transations',
            name='money_sent',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=12),
        ),
    ]
