# Generated by Django 3.0.3 on 2020-02-19 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NetBanking', '0002_auto_20200219_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transations',
            old_name='money_sent',
            new_name='moneysent',
        ),
    ]
