# Generated by Django 3.0.3 on 2020-02-24 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NetBanking', '0002_delete_accounttransactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactedtime', models.DateTimeField(auto_now_add=True)),
                ('moneydeposited', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('moneywithdrawed', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('active_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NetBanking.Account')),
            ],
        ),
    ]
