# Generated by Django 3.0.3 on 2020-02-19 05:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.PositiveIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999)])),
                ('pin', models.CharField(blank=True, help_text='Required. 6 characters or fewer. Letters, digits and special characters', max_length=6, null=True, verbose_name='pin')),
                ('balance', models.DecimalField(decimal_places=5, default=2000, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('username', models.CharField(blank=True, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, null=True, unique=True, verbose_name='username')),
                ('DOB', models.DateField()),
                ('Address', models.TextField()),
                ('password', models.CharField(blank=True, help_text='Required. 30 characters or fewer. Letters, digits and special characters', max_length=30, null=True, verbose_name='password')),
            ],
        ),
        migrations.CreateModel(
            name='Transations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_sent', models.DecimalField(decimal_places=5, default=2000, max_digits=6)),
                ('reason', models.TextField(blank=True, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='NetBanking.Users')),
                ('receivers_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='NetBanking.Account')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='NetBanking.Users')),
                ('senders_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='NetBanking.Account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='NetBanking.Users'),
        ),
    ]
