# Generated by Django 3.0.3 on 2020-02-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetBanking', '0002_auto_20200219_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.IntegerField(default=2000),
        ),
    ]
