# Generated by Django 3.0.3 on 2020-02-20 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NetBanking', '0004_auto_20200220_0900'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transations',
            new_name='Transactions',
        ),
    ]
