# Generated by Django 3.0.3 on 2020-02-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetBanking', '0004_auto_20200219_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=5, max_digits=6),
        ),
    ]
